/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ClipboardToSlackPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// converter.ts
function escapeHtml(text) {
  return text.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}
function protectCodeBlocks(text) {
  const blocks = [];
  let idx = 0;
  text = text.replace(/```[\w]*\n([\s\S]*?)```/g, (_, code) => {
    const placeholder = `\0CODEBLOCK_${idx}\0`;
    blocks.push({
      placeholder,
      original: "```\n" + code + "```",
      html: `<pre>${escapeHtml(code.replace(/\n$/, ""))}</pre>`
    });
    idx++;
    return placeholder;
  });
  text = text.replace(/`([^`\n]+)`/g, (_, code) => {
    const placeholder = `\0CODEBLOCK_${idx}\0`;
    blocks.push({
      placeholder,
      original: "`" + code + "`",
      html: `<code>${escapeHtml(code)}</code>`
    });
    idx++;
    return placeholder;
  });
  return { text, blocks };
}
function restoreCodeBlocks(text, blocks, format) {
  for (const block of blocks) {
    text = text.replace(block.placeholder, format === "html" ? block.html : block.original);
  }
  return text;
}
function removeComments(text) {
  return text.replace(/%%[\s\S]*?%%/g, "");
}
function convertBlockMath(text) {
  return text.replace(/\$\$([\s\S]*?)\$\$/g, "```\n$1\n```");
}
function convertInlineMath(text) {
  return text.replace(/\$([^\$\n]+)\$/g, "`$1`");
}
function convertCallouts(text) {
  return text.replace(/^(>\s*)\[!(\w+)\]-?\s*(.*)/gm, (_, prefix, type, title) => {
    return `${prefix}${type.toUpperCase()}${title ? ": " + title : ""}`;
  });
}
function convertFootnotes(text) {
  const footnotes = {};
  text = text.replace(/^\[\^(\w+)\]:\s*(.+)$/gm, (_, id, content) => {
    footnotes[id] = content;
    return "";
  });
  text = text.replace(/\[\^(\w+)\]/g, (_, id) => {
    return footnotes[id] ? ` (${footnotes[id]})` : "";
  });
  return text;
}
function convertTable(text) {
  const tableRegex = /^\|(.+)\|\s*\n\|[\s\-:|]+\|\s*\n((?:\|.+\|\s*\n?)*)/gm;
  return text.replace(tableRegex, (_, headerRow, bodyRows) => {
    const headers = headerRow.split("|").map((h) => h.trim()).filter(Boolean);
    const rows = bodyRows.trim().split("\n").filter(Boolean);
    let result = "";
    for (const row of rows) {
      const cells = row.split("|").map((c) => c.trim()).filter(Boolean);
      const parts = [];
      for (let i = 0; i < cells.length && i < headers.length; i++) {
        parts.push(`${headers[i]}: ${cells[i]}`);
      }
      result += parts.join(" | ") + "\n";
    }
    return result;
  });
}
function removeBackslashEscapes(text) {
  return text.replace(/\\([.\-#*!>\[\](){}+_~`|])/g, "$1");
}
function convertAsteriskBullets(text) {
  return text.replace(/^(\s*)\*\s+/gm, "$1- ");
}
function cleanupExtraBlankLines(text) {
  return text.replace(/\n{3,}/g, "\n\n");
}
function markdownToHtml(text) {
  text = text.replace(/\*\*\*(.+?)\*\*\*/g, "<b><i>$1</i></b>");
  text = text.replace(/(?<!\*)\*(?!\*)(.+?)(?<!\*)\*(?!\*)/g, "<i>$1</i>");
  text = text.replace(/\*\*(.+?)\*\*/g, "<b>$1</b>");
  text = text.replace(/~~(.+?)~~/g, "<s>$1</s>");
  text = text.replace(/==(.+?)==/g, "<b>$1</b>");
  text = text.replace(/!\[([^\]]*)\]\(([^)]+)\)/g, '<a href="$2">$1</a>');
  text = text.replace(/\[([^\]]+)\]\(([^)]+)\)/g, '<a href="$2">$1</a>');
  text = text.replace(/!\[\[([^\]|]+)(?:\|([^\]]+))?\]\]/g, (_, name, alias) => alias || name);
  text = text.replace(/\[\[([^\]|]+)(?:\|([^\]]+))?\]\]/g, (_, name, alias) => alias || name);
  text = text.replace(/^#{1,6}\s+(.+)$/gm, (_, content) => {
    const stripped = content.replace(/<\/?[bi]>/g, "");
    return `<b>${stripped}</b>`;
  });
  text = text.replace(/^(\s*)-\s*\[x\]\s*/gm, "$1\u2611 ");
  text = text.replace(/^(\s*)-\s*\[ \]\s*/gm, "$1\u2610 ");
  text = text.replace(/^-{3,}$/gm, "\u2500\u2500\u2500\u2500\u2500\u2500\u2500");
  return text;
}
function getIndentLevel(spaces) {
  const tabCount = (spaces.match(/\t/g) || []).length;
  const spaceCount = spaces.replace(/\t/g, "").length;
  return tabCount + Math.floor(spaceCount / 2);
}
var NBSP = "\xA0";
var INDENT = NBSP.repeat(4);
var BULLETS = ["\u2022", "\u25E6", "\u25AA", "\u25B9"];
function getBullet(level) {
  return BULLETS[Math.min(level, BULLETS.length - 1)];
}
function convertBlockElements(text) {
  const lines = text.split("\n");
  const result = [];
  for (const line of lines) {
    const unorderedMatch = line.match(/^(\s*)- (.+)$/);
    const checkboxMatch = line.match(/^(\s*)(☑|☐) (.+)$/);
    const orderedMatch = line.match(/^(\s*)(\d+)\.\s+(.+)$/);
    if (unorderedMatch) {
      const level = getIndentLevel(unorderedMatch[1]);
      const indent = INDENT.repeat(level);
      const bullet = getBullet(level);
      result.push(`${indent}${bullet} ${unorderedMatch[2]}`);
    } else if (checkboxMatch) {
      const level = getIndentLevel(checkboxMatch[1]);
      const indent = INDENT.repeat(level);
      result.push(`${indent}${checkboxMatch[2]} ${checkboxMatch[3]}`);
    } else if (orderedMatch) {
      const level = getIndentLevel(orderedMatch[1]);
      const indent = INDENT.repeat(level);
      result.push(`${indent}${orderedMatch[2]}. ${orderedMatch[3]}`);
    } else if (line.startsWith("> ")) {
      result.push(`<blockquote>${line.slice(2)}</blockquote>`);
    } else {
      result.push(line);
    }
  }
  return result.join("\n");
}
function convertToSlackHtml(text) {
  const { text: protectedText, blocks } = protectCodeBlocks(text);
  let result = protectedText;
  result = removeComments(result);
  result = convertBlockMath(result);
  result = convertInlineMath(result);
  result = convertCallouts(result);
  result = convertFootnotes(result);
  result = convertTable(result);
  result = removeBackslashEscapes(result);
  result = convertAsteriskBullets(result);
  result = markdownToHtml(result);
  result = convertBlockElements(result);
  result = restoreCodeBlocks(result, blocks, "html");
  result = cleanupExtraBlankLines(result);
  result = result.replace(/\n/g, "<br>");
  return result.trim();
}
function convertToSlackMrkdwn(text) {
  const { text: protectedText, blocks } = protectCodeBlocks(text);
  let result = protectedText;
  result = removeComments(result);
  result = convertBlockMath(result);
  result = convertInlineMath(result);
  result = convertCallouts(result);
  result = convertFootnotes(result);
  result = convertTable(result);
  result = removeBackslashEscapes(result);
  result = convertAsteriskBullets(result);
  result = result.replace(/\*\*\*(.+?)\*\*\*/g, "_$1_");
  result = result.replace(/(?<!\*)\*(?!\*)(.+?)(?<!\*)\*(?!\*)/g, "_$1_");
  result = result.replace(/\*\*(.+?)\*\*/g, "*$1*");
  result = result.replace(/\x01/g, "*");
  result = result.replace(/~~(.+?)~~/g, "~$1~");
  result = result.replace(/==(.+?)==/g, "*$1*");
  result = result.replace(/!\[([^\]]*)\]\(([^)]+)\)/g, "<$2|$1>");
  result = result.replace(/\[([^\]]+)\]\(([^)]+)\)/g, "<$2|$1>");
  result = result.replace(/!\[\[([^\]|]+)(?:\|([^\]]+))?\]\]/g, (_, name, alias) => alias || name);
  result = result.replace(/\[\[([^\]|]+)(?:\|([^\]]+))?\]\]/g, (_, name, alias) => alias || name);
  result = result.replace(/^#{1,6}\s+(.+)$/gm, (_, content) => {
    const stripped = content.replace(/^\*+|\*+$/g, "").replace(/^_+|_+$/g, "");
    return `*${stripped}*`;
  });
  result = result.replace(/^(\s*)-\s*\[x\]\s*/gm, "$1\u2611 ");
  result = result.replace(/^(\s*)-\s*\[ \]\s*/gm, "$1\u2610 ");
  result = result.replace(/^-{3,}$/gm, "\u2500\u2500\u2500\u2500\u2500\u2500\u2500");
  result = restoreCodeBlocks(result, blocks, "mrkdwn");
  result = cleanupExtraBlankLines(result);
  return result.trim();
}

// previewModal.ts
var import_obsidian = require("obsidian");
var SlackPreviewModal = class extends import_obsidian.Modal {
  constructor(app, original, htmlContent, mrkdwnContent) {
    super(app);
    this.original = original;
    this.htmlContent = htmlContent;
    this.mrkdwnContent = mrkdwnContent;
  }
  onOpen() {
    const { contentEl } = this;
    this.modalEl.addClass("mod-slack-preview");
    contentEl.addClass("slack-preview-modal");
    contentEl.createEl("h2", { text: "Slack \uD615\uC2DD \uBBF8\uB9AC\uBCF4\uAE30" });
    const container = contentEl.createDiv({ cls: "slack-preview-container" });
    const originalSection = container.createDiv({ cls: "slack-preview-section" });
    originalSection.createEl("h3", { text: "\uC6D0\uBCF8 (Obsidian)" });
    const originalPre = originalSection.createEl("pre", { cls: "slack-preview-code" });
    originalPre.createEl("code", { text: this.original });
    const convertedSection = container.createDiv({ cls: "slack-preview-section" });
    convertedSection.createEl("h3", { text: "\uBCC0\uD658 \uBBF8\uB9AC\uBCF4\uAE30 (Slack)" });
    const previewDiv = convertedSection.createDiv({ cls: "slack-preview-rendered" });
    previewDiv.innerHTML = this.htmlContent;
    const buttonContainer = contentEl.createDiv({ cls: "slack-preview-buttons" });
    const copyButton = buttonContainer.createEl("button", {
      text: "\uD074\uB9BD\uBCF4\uB4DC\uC5D0 \uBCF5\uC0AC",
      cls: "mod-cta"
    });
    copyButton.addEventListener("click", async () => {
      const blob = new Blob([this.htmlContent], { type: "text/html" });
      const textBlob = new Blob([this.mrkdwnContent], { type: "text/plain" });
      await navigator.clipboard.write([
        new ClipboardItem({
          "text/html": blob,
          "text/plain": textBlob
        })
      ]);
      new import_obsidian.Notice("Slack \uD615\uC2DD\uC73C\uB85C \uD074\uB9BD\uBCF4\uB4DC\uC5D0 \uBCF5\uC0AC\uB418\uC5C8\uC2B5\uB2C8\uB2E4");
      this.close();
    });
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// main.ts
async function copyToClipboard(html, mrkdwn) {
  const blob = new Blob([html], { type: "text/html" });
  const textBlob = new Blob([mrkdwn], { type: "text/plain" });
  await navigator.clipboard.write([
    new ClipboardItem({
      "text/html": blob,
      "text/plain": textBlob
    })
  ]);
}
function getSelection(plugin) {
  const view = plugin.app.workspace.getActiveViewOfType(import_obsidian2.MarkdownView);
  if (!view) {
    new import_obsidian2.Notice("\uB9C8\uD06C\uB2E4\uC6B4 \uC5D0\uB514\uD130\uB97C \uBA3C\uC800 \uC5F4\uC5B4\uC8FC\uC138\uC694");
    return null;
  }
  const selection = view.editor.getSelection();
  if (!selection) {
    new import_obsidian2.Notice("\uD14D\uC2A4\uD2B8\uB97C \uBA3C\uC800 \uC120\uD0DD\uD574\uC8FC\uC138\uC694");
    return null;
  }
  return selection;
}
var ClipboardToSlackPlugin = class extends import_obsidian2.Plugin {
  async onload() {
    this.addRibbonIcon("message-square", "Copy as Slack format", () => {
      const selection = getSelection(this);
      if (!selection)
        return;
      const html = convertToSlackHtml(selection);
      const mrkdwn = convertToSlackMrkdwn(selection);
      new SlackPreviewModal(this.app, selection, html, mrkdwn).open();
    });
    this.addCommand({
      id: "copy-as-slack-preview",
      name: "Copy as Slack format (\uBBF8\uB9AC\uBCF4\uAE30)",
      editorCallback: (editor) => {
        const selection = editor.getSelection();
        if (!selection) {
          new import_obsidian2.Notice("\uD14D\uC2A4\uD2B8\uB97C \uBA3C\uC800 \uC120\uD0DD\uD574\uC8FC\uC138\uC694");
          return;
        }
        const html = convertToSlackHtml(selection);
        const mrkdwn = convertToSlackMrkdwn(selection);
        new SlackPreviewModal(this.app, selection, html, mrkdwn).open();
      }
    });
    this.addCommand({
      id: "copy-as-slack-direct",
      name: "Copy as Slack format (\uBC14\uB85C \uBCF5\uC0AC)",
      hotkeys: [{ modifiers: ["Alt", "Shift"], key: "c" }],
      editorCallback: async (editor) => {
        const selection = editor.getSelection();
        if (!selection) {
          new import_obsidian2.Notice("\uD14D\uC2A4\uD2B8\uB97C \uBA3C\uC800 \uC120\uD0DD\uD574\uC8FC\uC138\uC694");
          return;
        }
        const html = convertToSlackHtml(selection);
        const mrkdwn = convertToSlackMrkdwn(selection);
        await copyToClipboard(html, mrkdwn);
        new import_obsidian2.Notice("Slack \uD615\uC2DD\uC73C\uB85C \uD074\uB9BD\uBCF4\uB4DC\uC5D0 \uBCF5\uC0AC\uB418\uC5C8\uC2B5\uB2C8\uB2E4");
      }
    });
  }
  onunload() {
  }
};
