/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ClipboardToSlackPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// converter.ts
function protectCodeBlocks(text) {
  const blocks = [];
  let idx = 0;
  text = text.replace(/```[\w]*\n([\s\S]*?)```/g, (_, code) => {
    const placeholder = `\0CODEBLOCK_${idx}\0`;
    blocks.push({ placeholder, content: "```\n" + code + "```" });
    idx++;
    return placeholder;
  });
  text = text.replace(/`([^`\n]+)`/g, (match) => {
    const placeholder = `\0CODEBLOCK_${idx}\0`;
    blocks.push({ placeholder, content: match });
    idx++;
    return placeholder;
  });
  return { text, blocks };
}
function restoreCodeBlocks(text, blocks) {
  for (const block of blocks) {
    text = text.replace(block.placeholder, block.content);
  }
  return text;
}
function removeComments(text) {
  return text.replace(/%%[\s\S]*?%%/g, "");
}
function convertBlockMath(text) {
  return text.replace(/\$\$([\s\S]*?)\$\$/g, "```\n$1\n```");
}
function convertInlineMath(text) {
  return text.replace(/\$([^\$\n]+)\$/g, "`$1`");
}
function convertCallouts(text) {
  return text.replace(/^(>\s*)\[!(\w+)\]-?\s*(.*)/gm, (_, prefix, type, title) => {
    return `${prefix}${type.toUpperCase()}${title ? ": " + title : ""}`;
  });
}
function convertFootnotes(text) {
  const footnotes = {};
  text = text.replace(/^\[\^(\w+)\]:\s*(.+)$/gm, (_, id, content) => {
    footnotes[id] = content;
    return "";
  });
  text = text.replace(/\[\^(\w+)\]/g, (_, id) => {
    return footnotes[id] ? ` (${footnotes[id]})` : "";
  });
  return text;
}
function convertTable(text) {
  const tableRegex = /^\|(.+)\|\s*\n\|[\s\-:|]+\|\s*\n((?:\|.+\|\s*\n?)*)/gm;
  return text.replace(tableRegex, (_, headerRow, bodyRows) => {
    const headers = headerRow.split("|").map((h) => h.trim()).filter(Boolean);
    const rows = bodyRows.trim().split("\n").filter(Boolean);
    let result = "";
    for (const row of rows) {
      const cells = row.split("|").map((c) => c.trim()).filter(Boolean);
      const parts = [];
      for (let i = 0; i < cells.length && i < headers.length; i++) {
        parts.push(`${headers[i]}: ${cells[i]}`);
      }
      result += parts.join(" | ") + "\n";
    }
    return result;
  });
}
function convertBoldItalic(text) {
  return text.replace(/\*\*\*(.+?)\*\*\*/g, "*_$1_*");
}
function convertBold(text) {
  return text.replace(/\*\*(.+?)\*\*/g, "*$1*");
}
function convertItalic(text) {
  return text.replace(/(?<!\w)\*(?!\s)(.+?)(?<!\s)\*(?!\w)/g, "_$1_");
}
function convertStrikethrough(text) {
  return text.replace(/~~(.+?)~~/g, "~$1~");
}
function convertHighlight(text) {
  return text.replace(/==(.+?)==/g, "*$1*");
}
function convertMarkdownLinks(text) {
  return text.replace(/\[([^\]]+)\]\(([^)]+)\)/g, "<$2|$1>");
}
function convertImages(text) {
  return text.replace(/!\[([^\]]*)\]\(([^)]+)\)/g, "<$2|$1>");
}
function convertEmbeds(text) {
  return text.replace(/!\[\[([^\]|]+)(?:\|([^\]]+))?\]\]/g, (_, name, alias) => {
    return alias || name;
  });
}
function convertWikiLinks(text) {
  return text.replace(/\[\[([^\]|]+)(?:\|([^\]]+))?\]\]/g, (_, name, alias) => {
    return alias || name;
  });
}
function convertHeadings(text) {
  return text.replace(/^#{1,6}\s+(.+)$/gm, "*$1*");
}
function convertCheckboxes(text) {
  text = text.replace(/^(\s*)-\s*\[x\]\s*/gm, "$1\u2611 ");
  text = text.replace(/^(\s*)-\s*\[ \]\s*/gm, "$1\u2610 ");
  return text;
}
function convertHorizontalRule(text) {
  return text.replace(/^-{3,}$/gm, "\u2500\u2500\u2500\u2500\u2500\u2500\u2500");
}
function cleanupExtraBlankLines(text) {
  return text.replace(/\n{3,}/g, "\n\n");
}
function convertToSlackMrkdwn(text) {
  const { text: protectedText, blocks } = protectCodeBlocks(text);
  let result = protectedText;
  result = removeComments(result);
  result = convertBlockMath(result);
  result = convertInlineMath(result);
  result = convertCallouts(result);
  result = convertFootnotes(result);
  result = convertTable(result);
  result = convertBoldItalic(result);
  result = convertBold(result);
  result = convertItalic(result);
  result = convertStrikethrough(result);
  result = convertHighlight(result);
  result = convertImages(result);
  result = convertMarkdownLinks(result);
  result = convertEmbeds(result);
  result = convertWikiLinks(result);
  result = convertHeadings(result);
  result = convertCheckboxes(result);
  result = convertHorizontalRule(result);
  result = restoreCodeBlocks(result, blocks);
  result = cleanupExtraBlankLines(result);
  return result.trim();
}

// previewModal.ts
var import_obsidian = require("obsidian");
var SlackPreviewModal = class extends import_obsidian.Modal {
  constructor(app, original, converted) {
    super(app);
    this.original = original;
    this.converted = converted;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.addClass("slack-preview-modal");
    contentEl.createEl("h2", { text: "Slack \uD615\uC2DD \uBBF8\uB9AC\uBCF4\uAE30" });
    const container = contentEl.createDiv({ cls: "slack-preview-container" });
    const originalSection = container.createDiv({ cls: "slack-preview-section" });
    originalSection.createEl("h3", { text: "\uC6D0\uBCF8 (Obsidian)" });
    const originalPre = originalSection.createEl("pre", { cls: "slack-preview-code" });
    originalPre.createEl("code", { text: this.original });
    const convertedSection = container.createDiv({ cls: "slack-preview-section" });
    convertedSection.createEl("h3", { text: "\uBCC0\uD658 (Slack mrkdwn)" });
    const convertedPre = convertedSection.createEl("pre", { cls: "slack-preview-code" });
    convertedPre.createEl("code", { text: this.converted });
    const buttonContainer = contentEl.createDiv({ cls: "slack-preview-buttons" });
    const copyButton = buttonContainer.createEl("button", {
      text: "\uD074\uB9BD\uBCF4\uB4DC\uC5D0 \uBCF5\uC0AC",
      cls: "mod-cta"
    });
    copyButton.addEventListener("click", async () => {
      await navigator.clipboard.writeText(this.converted);
      new import_obsidian.Notice("Slack \uD615\uC2DD\uC73C\uB85C \uD074\uB9BD\uBCF4\uB4DC\uC5D0 \uBCF5\uC0AC\uB418\uC5C8\uC2B5\uB2C8\uB2E4");
      this.close();
    });
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// main.ts
var ClipboardToSlackPlugin = class extends import_obsidian2.Plugin {
  async onload() {
    this.addCommand({
      id: "copy-as-slack-format",
      name: "Copy as Slack format",
      editorCallback: (editor) => {
        const selection = editor.getSelection();
        if (!selection) {
          new import_obsidian2.Notice("\uD14D\uC2A4\uD2B8\uB97C \uBA3C\uC800 \uC120\uD0DD\uD574\uC8FC\uC138\uC694");
          return;
        }
        const converted = convertToSlackMrkdwn(selection);
        new SlackPreviewModal(this.app, selection, converted).open();
      }
    });
  }
  onunload() {
  }
};
